FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine
WORKDIR /app

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk add --no-cache prometheus-node-exporter

# Expose the port Prometheus uses
EXPOSE 9100

RUN mkdir -p /app/customs/
COPY customs/*.prom /app/customs/
COPY *.sh /app/

# Start Node Exporter
CMD [ "/usr/bin/node_exporter", "--collector.textfile.directory=/app/customs" ]

